"""Added Stack.es_doc_id; the same place -- question and answer are TEXT now, removed is_deleted flag

Revision ID: 0003
Revises: 0002
Create Date: 2023-03-01 14:12:27.808008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('es_doc_id', sa.String(length=32), nullable=True))
    op.alter_column('cards', 'question',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('cards', 'answer',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('cards', 'deleted')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('cards', 'answer',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('cards', 'question',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('cards', 'es_doc_id')
    # ### end Alembic commands ###
